version: '3'

networks:
    jarch-infra-global-network-proxy-admin:
      external: true

services:
 
  ui:
    image: sonatype/nexus3:3.6.0
    ports:
      - 8185:8081
    networks:
      - jarch-infra-global-network-proxy-admin
    volumes:
      - /usr/local/jra/docker-data-volumes/jra-infra/repo-nexus/home:/nexus-data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.jra.swarm-node-type == infra-repos]
      labels:
        - "traefik.docker.network=jarch-infra-global-network-proxy-admin"
        - "traefik.port=8081"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}nexus.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-repos-nexus"
        - "jra.container-name=jarch-infra-repos-nexus"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}nexus.joericearchitect.com"
