version: '3'

networks:
  network-proxy:
  network-app:
  jarch-infra-global-network-monitoring:
    external: true

services:
 
  proxy:
    image: traefik:v1.4.2
    ports:
      - 81:80
      - 8188:8080
    networks:
      - network-proxy
    command:
      - --docker
      - --docker.swarmmode
      - --docker.domain=traefik
      - --docker.watch
      - --web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=jarch-infra-logging_network-proxy"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}logging-proxy.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-logging-proxy"
        - "jra.container-name=jarch-infra-logging-logging-proxy"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}logging-proxy.joericearchitect.com"

  elasticsearch:
    image: joericearchitect/jarch-infra-elasticsearch:1.0.0
    ports:
      - 8191:9200
      - 8192:9300
    networks:
      - network-proxy
      - network-app
      - jarch-infra-global-network-monitoring
    environment:
      - xpack.security.enabled=false
    command:
      - elasticsearch
    volumes:
      - /usr/local/jra/docker-data-volumes/jra-infra/logging-elasticsearch/data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.jra.swarm-node-type == infra-logging]
      labels:
        - "traefik.docker.network=jarch-infra-logging_network-proxy"
        - "traefik.port=9200"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}es.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-logging-elasticsearch"
        - "jra.container-name=jarch-infra-logging-elasticsearch"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}es.joericearchitect.com"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    depends_on:
      - elasticsearch
    ports:
      - 8187:5601
    networks:
      - network-proxy
      - network-app
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.jra.swarm-node-type == infra-logging]
      labels:
        - "traefik.docker.network=jarch-infra-logging_network-proxy"
        - "traefik.port=5601"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}kibana.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-logging-kibana"
        - "jra.container-name=jarch-infra-logging-kibana"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}kibana.joericearchitect.com"

  fluentd:
    image: joericearchitect/jarch-infra-fluentd-es
    depends_on:
      - elasticsearch
    ports:
      - 8182:24224
    networks:
      - network-proxy
      - network-app
    volumes:
      - /usr/local/jra/docker-data-volumes/jra-infra/logging-fluentd/data:/fluentd/log
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.jra.swarm-node-type == infra-logging]
      labels:
        - "traefik.docker.network=jarch-infra-logging_network-proxy"
        - "traefik.port=24284"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}fluentd.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-logging-fluentd"
        - "jra.container-name=jarch-infra-logging-fluentd"
        - "jra.domain-name=${ENV_DOMAIN_PREFIX}fluentd.joericearchitect.com"
